const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function setupTheme(){const saved=localStorage.getItem('theme')||'light';document.documentElement.dataset.theme=saved;const b=$('[data-theme-toggle]');if(b)b.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('theme',next);b.textContent=next==='dark'?'☀️':'🌙'})}
function setupNav(){const m=$('.menu-btn'),links=$('.nav-links');m?.addEventListener('click',()=>links?.classList.toggle('open'));$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));const path=location.pathname.split('/').pop()||'index.html';$$('.nav-links a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});}
function setupReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el))}
function setupCounters(){const els=$$('[data-counter]');const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target, target=Number(el.dataset.counter)||0;let n=0;const step=Math.max(1,Math.ceil(target/45));const t=setInterval(()=>{n=Math.min(target,n+step);el.textContent=n+(el.dataset.suffix||'');if(n>=target)clearInterval(t)},22);io.unobserve(el)}),{threshold:.6});els.forEach(e=>io.observe(e))}
function init(){setupTheme();setupNav();setupReveal();setupCounters();}
document.addEventListener('DOMContentLoaded',init);
window.App={$, $$, store};
function setupSearch(){const input=$('[data-search]'),results=$('[data-search-results]');if(!input||!results)return;const items=JSON.parse(input.dataset.items||'[]');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='';return}const matches=items.filter(x=>`${x.title} ${x.category} ${x.desc}`.toLowerCase().includes(q)).slice(0,8);results.innerHTML=matches.length?matches.map(x=>`<div class="search-result"><strong>${x.title}</strong><div style="font-size:.78rem;color:var(--muted)">${x.category}</div><div style="font-size:.84rem;color:var(--muted)">${x.desc}</div></div>`).join(''):`<div class="empty">No matching roadmap item found.</div>`})}
document.addEventListener('DOMContentLoaded',setupSearch);
