const internshipItems=['Resume Ready','LinkedIn Profile','GitHub Profile','Portfolio Website','2+ Projects','1 Major Project','DSA Practice','Communication Skills','Mock Interview','Internship Applications'];
const dailyItems=['Solve DSA problems','Learn a new concept','Code for 1 hour','Work on a project','Read technical documentation','Practice communication'];
function listCheck(containerId,key,items){const box=App.$('#'+containerId);if(!box)return;const saved=App.store.get(key,{});box.innerHTML=items.map((x,i)=>`<label class="check-item ${saved[i]?'done':''}"><input type="checkbox" data-k="${i}" ${saved[i]?'checked':''}><span>${x}</span></label>`).join('');box.querySelectorAll('input').forEach(ch=>ch.addEventListener('change',()=>{saved[ch.dataset.k]=ch.checked;App.store.set(key,saved);ch.parentElement.classList.toggle('done',ch.checked);window.updateOverall?.()}));return items.length}
function getPct(key,total){const d=App.store.get(key,{});return total?Math.round(Object.values(d).filter(Boolean).length/total*100):0}
function updateIntern(){const pct=getPct('internshipDone',internshipItems.length);if(App.$('#internship-percent'))App.$('#internship-percent').textContent=pct+'%';if(App.$('#internship-bar'))App.$('#internship-bar').style.width=pct+'%'}
function updateOverall(){const dsa=App.store.get('dsaDone',{}),int=App.store.get('internshipDone',{}),daily=App.store.get('dailyDone',{}),inter=App.store.get('interviewDone',{}),proj=App.store.get('projectStatus',{});const vals=[Object.values(dsa).filter(Boolean).length/dsaCount(),Object.values(int).filter(Boolean).length/internshipItems.length,Object.values(inter).filter(Boolean).length/interviewCount(),Object.values(proj).filter(v=>v==='Completed').length/projectCount()].filter(v=>!Number.isNaN(v));const overall=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*100):0;const targets=[['#overall-percent',overall],['#overall-bar',overall],['#daily-percent',getDailyPct()]];targets.forEach(([s,v])=>{const el=App.$(s);if(el)el.style?el.style.width=v+'%':el.textContent=v+'%'});const text=App.$('#overall-percent');if(text)text.textContent=overall+'%';const circle=App.$('#overall-circle');if(circle)circle.style.background=`conic-gradient(var(--primary) ${overall*3.6}deg,var(--surface2) 0deg)`;window.updateYearBars?.()}
const dsaCount=()=>13,interviewCount=()=>10,projectCount=()=>12;
function getDailyPct(){const d=App.store.get('dailyDone',{});return Math.round(Object.values(d).filter(Boolean).length/dailyItems.length*100)}
function initTracker(){listCheck('internship-list','internshipDone',internshipItems);listCheck('daily-list','dailyDone',dailyItems);updateIntern();window.updateOverall=updateOverall;updateOverall();const modal=App.$('#modal');modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});}
document.addEventListener('DOMContentLoaded',initTracker);
